import PolicyLayout from './PolicyLayout'

export default function Terms() {
  return (
    <PolicyLayout title="Terms and Conditions" slug="terms">
      <div className="toc"><h2>Contents</h2><ol><li><a href="#s1">Nature of this document</a></li><li><a href="#s2">Definitions</a></li><li><a href="#s3">Eligibility and capacity</a></li><li><a href="#s4">User account</a></li><li><a href="#s5">Product information</a></li><li><a href="#s6">Price and charges</a></li><li><a href="#s7">Orders, acceptance and formation of contract</a></li><li><a href="#s8">Personal use, quantity limits and resale</a></li><li><a href="#s9">Pre-orders</a></li><li><a href="#s10">Payment</a></li><li><a href="#s11">Shipping and delivery</a></li><li><a href="#s12">Returns, refunds and cancellation</a></li><li><a href="#s13">Promotions, coupons, loyalty and referrals</a></li><li><a href="#s14">Reviews, ratings and user content</a></li><li><a href="#s15">Intellectual property</a></li><li><a href="#s16">Prohibited conduct</a></li><li><a href="#s17">Third-party services and links</a></li><li><a href="#s18">Warranties and disclaimer</a></li><li><a href="#s19">Customer's responsibilities for safe use</a></li><li><a href="#s20">Limitation of liability</a></li><li><a href="#s21">Indemnity</a></li><li><a href="#s22">Force majeure</a></li><li><a href="#s23">Communications and consent to contact</a></li><li><a href="#s24">Governing law and disputes</a></li><li><a href="#s25">Amendment</a></li><li><a href="#s26">General</a></li><li><a href="#s27">Contact</a></li></ol></div>
      <h2 id="s1">1. Nature of this Document</h2>
      <p>1.1 These Terms and Conditions of Use and Sale (<strong>"Terms"</strong>) constitute a legally binding agreement between Ember Global Fragrances Private Limited, a company incorporated under the Companies Act, 2013, bearing CIN U20234DC2026PTC468967 and GSTIN <span className="fill">TO BE FILLED &mdash; GSTIN</span>, having its registered office at 2nd Floor, B-265, Plot No. SU, North Ex-mall, Sector 9, Near Kadambari Apartment, Rohini, North West Delhi, Delhi 110085 (the <strong>"Company"</strong>, <strong>"LORIUS"</strong>, "we", "us" or "our", which expression includes its successors and permitted assigns), and any person who accesses, browses, registers on or places an order through the Website ("you", "your", "User" or "Customer").</p>
      <p>1.2 This document is an electronic record within the meaning of the Information Technology Act, 2000 and the rules made thereunder, as amended. It is generated by a computer system and does not require any physical or digital signature. It is published in accordance with Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, to the extent applicable, and the Consumer Protection (E-Commerce) Rules, 2020.</p>
      <p>1.3 By clicking "Place Order", "Pay Now", "Pre-order", "Sign Up" or any similar button, or by accessing or using the Website, you signify that you have read, understood and unconditionally accepted these Terms together with the following policies, each of which forms an integral part of these Terms and is incorporated by reference (the <strong>"Policies"</strong>):</p>
      <ul>
      <li><a href="#/privacy">Privacy Policy</a></li>
      <li><a href="#/shipping">Shipping and Delivery Policy</a></li>
      <li><a href="#/returns">Return, Refund and Cancellation Policy</a></li>
      <li><a href="#/payments">Payment Policy</a></li>
      <li><a href="#/cookies">Cookie Policy</a></li>
      <li><a href="#/disclaimer">Disclaimer</a></li>
      <li><a href="#/grievance">Grievance Redressal Policy</a></li>
      <li>any offer-specific terms published on the Website.</li>
      </ul>
      <p>1.4 In the event of any conflict between these Terms and a specific Policy, the specific Policy shall prevail in relation to its subject matter, and offer-specific terms shall prevail in relation to that offer.</p>
      <p>1.5 If you do not agree with any part of these Terms, you must not access the Website or place any order.</p>
      
      <h2 id="s2">2. Definitions</h2>
      <p>In these Terms, unless the context otherwise requires:</p>
      <ul>
      <li>(a) <strong>"Website"</strong> means www.loriusperfume.com, its sub-domains, mobile-optimised versions, any mobile application, WhatsApp or social-commerce storefront and any other digital interface owned or operated by the Company for the sale of LORIUS products;</li>
      <li>(b) <strong>"Products"</strong> means the LORIUS range of fragrances, including eau de parfum, gift sets, discovery sets, samples, accessories and any other goods offered for sale on the Website from time to time;</li>
      <li>(c) <strong>"Order"</strong> means a request by a customer to purchase Products through the Website, including a Pre-order;</li>
      <li>(d) <strong>"Pre-order"</strong> means an Order placed for a Product which is not yet available for dispatch as at the date of the Order and is so identified on the Website;</li>
      <li>(e) <strong>"Dispatch"</strong> means the handing over of the Product by the Company to the courier or logistics partner for delivery to the Customer;</li>
      <li>(f) <strong>"Business Day"</strong> means any day other than a Sunday or a gazetted public holiday in Delhi;</li>
      <li>(g) <strong>"Consumer"</strong> has the meaning assigned to it in section 2(7) of the Consumer Protection Act, 2019, and excludes a person who obtains Products for resale or for any commercial purpose;</li>
      <li>(h) <strong>"Business Purchaser"</strong> means any person who is not a Consumer, including a reseller, retailer, distributor, corporate buyer purchasing for commercial use, or any person purchasing in quantities exceeding the Permitted Quantity;</li>
      <li>(i) <strong>"Permitted Quantity"</strong> means the maximum quantity of any Product which may be purchased in a single Order or by a single Customer within a stated period, as displayed on the Website or determined under Clause 8;</li>
      <li>(j) <strong>"Applicable Law"</strong> means all laws, statutes, rules, regulations, notifications, guidelines and binding orders in force in India from time to time, as amended.</li>
      </ul>
      <p>Words in the singular include the plural and vice versa. Headings are for convenience only and do not affect interpretation. The words "including" and "include" are to be read without limitation.</p>
      
      <h2 id="s3">3. Eligibility and Capacity</h2>
      <p>3.1 Use of the Website and purchase of Products is available only to persons competent to contract within the meaning of the Indian Contract Act, 1872. Persons who are minors (under 18 years of age), undischarged insolvents, or otherwise incompetent to contract are not eligible to place Orders.</p>
      <p>3.2 A minor may browse the Website and use Products purchased by a parent or legal guardian only under the supervision of such parent or guardian, who shall be deemed to be the Customer and shall be responsible for compliance with these Terms.</p>
      <p>3.3 By placing an Order you represent and warrant that (a) you are at least 18 years of age; (b) all information furnished by you is true, accurate, current and complete; (c) you are purchasing the Products for personal use and not for resale, unless you are a Business Purchaser who has entered into a separate written arrangement with the Company; and (d) your use of the Website will not violate any Applicable Law.</p>
      <p>3.4 The Company reserves the right to refuse access to the Website, to refuse to accept or to cancel any Order, and to suspend or terminate any account where it has reasonable grounds to believe that any of the above representations is untrue.</p>
      
      <h2 id="s4">4. User Account</h2>
      <p>4.1 Certain features of the Website, including order history, tracking, saved addresses and loyalty benefits, require registration of a user account. You may also place Orders as a guest, in which case the obligations of these Terms apply equally.</p>
      <p>4.2 You are solely responsible for maintaining the confidentiality of your login credentials and one-time passwords, and for all activity conducted through your account. Any Order placed through your account shall be deemed to have been placed by you. You must notify the Company immediately at <span className="fill">TO BE FILLED &mdash; customer care e-mail</span> of any unauthorised use or security breach.</p>
      <p>4.3 You shall not (a) create more than one account; (b) create an account using false or another person's identity; (c) transfer, sell or share your account; or (d) create accounts for the purpose of availing first-order or referral offers multiple times.</p>
      <p>4.4 The Company may, at its discretion and without liability, suspend, restrict or terminate any account (including by disabling Cash on Delivery or return facilities) where it reasonably believes the account has been used for any of the following (<strong>"Account Abuse"</strong>):</p>
      <ul>
      <li>(a) fraudulent, false or exaggerated claims of damage, non-delivery or missing items;</li>
      <li>(b) repeated refusal of Cash on Delivery Orders without valid reason;</li>
      <li>(c) abuse of coupons, referral schemes, promotional pricing or free gifts;</li>
      <li>(d) chargebacks raised in bad faith after receipt of the Products;</li>
      <li>(e) purchases for commercial resale in breach of Clause 8;</li>
      <li>(f) abusive, threatening or defamatory communication with Company personnel; or</li>
      <li>(g) any breach of these Terms or Applicable Law.</li>
      </ul>
      <p>4.5 Suspension or termination of an account shall not affect any Order already dispatched, nor any refund lawfully due to you, which shall be processed in accordance with the <a href="#/returns">Return, Refund and Cancellation Policy</a>.</p>
      
      <h2 id="s5">5. Product Information</h2>
      <p>5.1 The Company makes reasonable efforts to ensure that all descriptions, images, fragrance notes, concentrations, volumes, prices and other information relating to the Products are accurate. Every product listing carries the declarations required under the Legal Metrology Act, 2009, the Legal Metrology (Packaged Commodities) Rules, 2011, the Drugs and Cosmetics Act, 1940 and the Cosmetics Rules, 2020, including the name and address of the manufacturer or marketer, net quantity, maximum retail price inclusive of all taxes, country of origin, best-before or expiry information, and the list of ingredients.</p>
      <p>5.2 You acknowledge that fragrance is inherently subjective and that:</p>
      <ul>
      <li>(a) descriptions of top, heart and base notes are artistic interpretations intended to guide, and not scientific specifications;</li>
      <li>(b) longevity, projection and sillage vary according to individual skin chemistry, skin type, body temperature, climate, humidity, diet, the quantity applied and the method of application, and any duration mentioned on the Website is indicative only;</li>
      <li>(c) the colour of the concentrate, bottle, cap and packaging may vary slightly between batches and from the images displayed, due to natural variation in raw materials, manufacturing tolerances and the display settings of your device;</li>
      <li>(d) natural and nature-identical ingredients may produce minor batch-to-batch variation in scent, colour and clarity, which shall not constitute a defect.</li>
      </ul>
      <p>5.3 The Company may, without prior notice, modify the packaging, bottle design, labelling or formulation of any Product, provided that such modification complies with Applicable Law and does not materially alter the essential character of the Product. Products delivered in updated packaging shall not be treated as "different from the Product ordered".</p>
      <p>5.4 All images, videos, lifestyle photographs and models used on the Website are for illustrative purposes. Props, accessories and other items shown in images are not included with the Product unless expressly stated.</p>
      <p>5.5 Products are intended for external cosmetic use only. Please read the <a href="#/disclaimer">Disclaimer</a> and the label before use.</p>
      
      <h2 id="s6">6. Price and Charges</h2>
      <p>6.1 All prices on the Website are in Indian Rupees (INR) and are inclusive of Goods and Services Tax unless otherwise stated. Prices are not higher than the maximum retail price printed on the Product.</p>
      <p>6.2 Shipping charges, Cash on Delivery handling charges, gift-wrapping charges and any other charge, if applicable, are displayed separately and in full in the order summary before you make payment. The Company does not add any charge at any later stage of the checkout process.</p>
      <p>6.3 Prices, discounts and offers may be changed by the Company at any time without prior notice. The price applicable to your Order is the price displayed at the time the Order is placed, subject to Clause 6.4.</p>
      <p>6.4 <strong>Pricing and typographical errors.</strong> If a Product is listed at an incorrect price, or with incorrect information, owing to a typographical, technical or system error (including an error by a third-party service provider), the Company shall be entitled, at any time before Dispatch and even after an order confirmation has been sent, to cancel the Order. In such case the Company shall inform you and refund in full any amount received, without deduction, and shall have no further liability. You may alternatively be offered the option to purchase at the correct price.</p>
      <p>6.5 A reduction in price after you have placed an Order, or after delivery, shall not entitle you to a refund of the difference or to any credit, unless the Company expressly announces a price-protection scheme.</p>
      
      <h2 id="s7">7. Orders, Acceptance and Formation of Contract</h2>
      <p>7.1 Every Order placed by you constitutes an offer by you to purchase the Products at the price and on the terms displayed. Any acknowledgement or order confirmation sent by e-mail, SMS or WhatsApp merely confirms receipt of your offer and does not constitute acceptance.</p>
      <p>7.2 A binding contract of sale is formed only upon Dispatch of the Products, which constitutes acceptance of your offer. In the case of a Pre-order, the contract is formed upon Dispatch, although payment may be collected at the time of the Pre-order in accordance with Clause 9.</p>
      <p>7.3 The Company reserves the right, at any time before Dispatch, to refuse or cancel any Order, in whole or in part, including where:</p>
      <ul>
      <li>(a) the Product is out of stock or discontinued;</li>
      <li>(b) there is an error in price or product information;</li>
      <li>(c) the delivery address is not serviceable, is incomplete, or is a post-box or unverifiable address;</li>
      <li>(d) the Order exceeds the Permitted Quantity or the Company reasonably believes it is being placed for resale;</li>
      <li>(e) payment is not received, is reversed, or is flagged as potentially fraudulent by the Company, its payment aggregator or bank;</li>
      <li>(f) the Customer's account is subject to Account Abuse action;</li>
      <li>(g) the Order cannot be fulfilled due to a Force Majeure Event; or</li>
      <li>(h) fulfilment would be contrary to Applicable Law or to any order of a court or authority.</li>
      </ul>
      <p>7.4 Where an Order is cancelled by the Company under Clause 7.3, the Company shall refund the entire amount received for the cancelled Products, including any shipping charge paid for them, in accordance with the <a href="#/payments">Payment Policy</a>, without levying any cancellation charge. Beyond such refund the Company shall have no liability for the cancellation.</p>
      <p>7.5 The Company may partially fulfil an Order and ship Products in more than one consignment. Each consignment shall be treated as a separate contract for the purposes of delivery and claims.</p>
      
      <h2 id="s8">8. Personal Use, Quantity Limits and Prohibition on Resale</h2>
      <p>8.1 Products sold on the Website are intended solely for the personal, non-commercial use of the Customer and their family and friends, including as gifts.</p>
      <p>8.2 The Company may prescribe a Permitted Quantity for any Product or for Orders generally. In the absence of a displayed limit, the Company may treat an Order of more than five (5) units of the same Product, or several Orders to the same address, telephone number, account or payment instrument within a short period, as a potential commercial order.</p>
      <p>8.3 Business Purchasers may purchase only under a separate written agreement with the Company. Please write to <span className="fill">TO BE FILLED &mdash; business / trade enquiries e-mail</span> for trade, bulk, gifting and corporate enquiries.</p>
      <p>8.4 The Company does not warrant, and shall have no liability for, any Product purchased from any person other than the Company or its authorised channel partners, including Products resold by a Customer in breach of this Clause. The Company reserves all rights to take action against unauthorised resale, parallel trade, tampering, refilling or repackaging of its Products.</p>
      
      <h2 id="s9">9. Pre-orders</h2>
      <p>9.1 Products identified on the Website as available for Pre-order have not yet been released for Dispatch. The anticipated date from which Dispatch will commence (currently <strong>23 October 2026</strong>, or such other date as is displayed) is stated on the product page and in your Pre-order confirmation. The date is a good-faith estimate and is not of the essence of the contract, subject to Clause 9.4.</p>
      <p>9.2 Pre-orders may be paid for in full at the time of placing the Pre-order, or by payment of a booking amount with the balance on or before Dispatch, as displayed at checkout. Cash on Delivery may not be available for Pre-orders.</p>
      <p>9.3 Pre-orders shall be fulfilled substantially in the sequence in which they are received, subject to stock allocation, serviceability and logistics.</p>
      <p>9.4 If the Company anticipates that Dispatch will be delayed beyond the date communicated, it shall notify you by e-mail and/or SMS or WhatsApp with a revised date. You may then elect either to continue with the Pre-order or to cancel it and receive a full refund. If you do not respond within seven (7) days of the notice, the Pre-order shall continue on the revised date. If the delay exceeds forty-five (45) days beyond the originally communicated date, the Company shall refund the Pre-order in full unless you have expressly confirmed that you wish to continue.</p>
      <p>9.5 A Pre-order may be cancelled by you at any time before Dispatch, and a full refund shall be made without any cancellation charge.</p>
      <p>9.6 The Pre-order price is fixed at the time of the Pre-order. Any price reduction or promotional offer introduced subsequently shall not apply to existing Pre-orders unless the Company expressly so provides.</p>
      <p>9.7 Limited-edition or launch-exclusive benefits offered with Pre-orders, such as complimentary samples or engraving, are subject to availability and may be substituted with benefits of equal or greater value.</p>
      
      <h2 id="s10">10. Payment</h2>
      <p>Payment terms are governed by the <a href="#/payments">Payment Policy</a>, which forms part of these Terms. Title to the Products passes to you upon receipt of full payment and delivery; risk passes to you upon delivery at the shipping address specified in the Order.</p>
      
      <h2 id="s11">11. Shipping and Delivery</h2>
      <p>Shipping, delivery timelines, charges, delivery attempts and return-to-origin consequences are governed by the <a href="#/shipping">Shipping and Delivery Policy</a>. Delivery timelines are estimates, and the Company shall not be liable for delay caused by the courier, the Customer or a Force Majeure Event, save as provided in the <a href="#/returns">Return, Refund and Cancellation Policy</a>.</p>
      
      <h2 id="s12">12. Returns, Refunds and Cancellation</h2>
      <p>Returns, refunds, replacements and cancellations are governed exclusively by the <a href="#/returns">Return, Refund and Cancellation Policy</a>. You acknowledge that, owing to the hygienic and personal nature of fragrance products, the Company does not accept returns for change of mind, fragrance preference or skin compatibility, and that the remedies set out in that Policy for damaged, defective, incorrect or short-delivered Products are the remedies available to you, without prejudice to your non-waivable rights under Applicable Law.</p>
      
      <h2 id="s13">13. Promotions, Coupons, Loyalty and Referral Programmes</h2>
      <p>13.1 Promotional offers, discount codes, coupons, free gifts, bundles, loyalty points and referral rewards (<strong>"Promotions"</strong>) are offered at the sole discretion of the Company, are subject to the specific terms displayed with them, and may be modified, suspended or withdrawn at any time without prior notice, save that a Promotion validly applied to an Order already placed shall be honoured.</p>
      <p>13.2 Unless otherwise stated: (a) only one coupon may be applied per Order; (b) Promotions cannot be combined; (c) coupons have no cash value and are not transferable; (d) Promotions do not apply to taxes, shipping or gift-wrapping charges; and (e) Promotions are limited to one per Customer, household, device or payment instrument.</p>
      <p>13.3 Free gifts and complimentary samples are provided subject to availability and carry no monetary value. They are not eligible for return, exchange or refund, and if a Product is returned or refunded, the free gift (or its value, where it cannot be returned) shall also be returned or deducted.</p>
      <p>13.4 If an Order in which a Promotion was availed is partially returned or cancelled, the benefit of the Promotion may be recalculated and the refund reduced accordingly, where the remaining Order no longer satisfies the conditions of the Promotion.</p>
      <p>13.5 The Company may cancel any Order, reverse any benefit and suspend any account where it reasonably believes that a Promotion has been availed fraudulently, through multiple accounts, automated means, or in breach of its terms.</p>
      <p>13.6 The Company does not use false urgency, fake scarcity timers, hidden charges, pre-ticked add-ons or any other practice prohibited by the Guidelines for Prevention and Regulation of Dark Patterns, 2023. Any countdown, "limited stock" or similar indicator on the Website reflects genuine conditions.</p>
      
      <h2 id="s14">14. Reviews, Ratings and User Content</h2>
      <p>14.1 You may post reviews, ratings, photographs, videos, comments and other content (<strong>"User Content"</strong>) on the Website or tag the Company on social media. You are solely responsible for your User Content and represent that it is truthful, based on your genuine experience, owned by you, and does not infringe any law or third-party right.</p>
      <p>14.2 By posting User Content or tagging the Company, you grant the Company a worldwide, perpetual, irrevocable, royalty-free, non-exclusive, sub-licensable and transferable licence to use, reproduce, adapt, edit (for length and clarity only, without changing meaning), publish, translate, distribute and display such User Content in any media, including for marketing, with or without attribution. You waive any moral rights to the extent permitted by law. Where the User Content includes your likeness, the Company will seek your consent before using it in paid advertising.</p>
      <p>14.3 The Company publishes genuine reviews, whether positive or negative, in accordance with the Consumer Protection (E-Commerce) Rules, 2020 and IS 19000:2022 on online consumer reviews, and does not suppress reviews merely because they are unfavourable. The Company may, however, decline to publish or may remove User Content that: (a) is abusive, obscene, defamatory, hateful or unlawful; (b) is unrelated to the Product; (c) contains personal data of others, links or advertising; (d) is posted by competitors, employees or persons who have not purchased the Product without disclosure; (e) is incentivised without disclosure; or (f) is duplicative or spam.</p>
      <p>14.4 You shall not post fake reviews, pay for or solicit reviews in exchange for undisclosed benefits, or use User Content to defame the Company or its Products. The Company reserves the right to pursue its remedies under Applicable Law against false or malicious User Content.</p>
      
      <h2 id="s15">15. Intellectual Property</h2>
      <p>15.1 The trade mark "LORIUS", the LORIUS logo and medallion, the tagline "Happiness. Confidence. Success.", the product names used for the Company's fragrances, the bottle shapes, cap designs, packaging, trade dress, photographs, videos, text, graphics, fragrance descriptions, software, source code and the compilation and arrangement of content on the Website (<strong>"Company IP"</strong>) are owned by or licensed to the Company and are protected under the Trade Marks Act, 1999, the Copyright Act, 1957, the Designs Act, 2000 and other Applicable Law.</p>
      <p>15.2 You are granted a limited, revocable, non-exclusive, non-transferable licence to access and view the Website for personal, non-commercial purposes only. Nothing in these Terms grants any other right in the Company IP.</p>
      <p>15.3 You shall not: (a) copy, reproduce, frame, mirror, scrape or republish any part of the Website; (b) use the Company IP in any meta-tag, domain name, social-media handle, keyword advertisement or product listing; (c) sell or advertise any product as "inspired by", "equivalent to", "dupe of" or "impression of" LORIUS; (d) refill, decant, repackage or relabel Products for sale; or (e) remove any proprietary notice.</p>
      <p>15.4 Any unauthorised use of the Company IP shall constitute infringement or passing off, and the Company reserves the right to seek injunctive relief, damages, delivery-up and costs.</p>
      
      <h2 id="s16">16. Prohibited Conduct</h2>
      <p>You agree not to, and not to permit any person to:</p>
      <ul>
      <li>(a) use the Website for any unlawful purpose or in violation of these Terms;</li>
      <li>(b) use any robot, spider, scraper, crawler or automated means to access, monitor or copy the Website or to place Orders;</li>
      <li>(c) interfere with, disrupt, overload, probe, scan or test the vulnerability of the Website or circumvent any security measure;</li>
      <li>(d) upload or transmit viruses, malware or any harmful code;</li>
      <li>(e) impersonate any person or misrepresent your affiliation;</li>
      <li>(f) use any payment instrument that you are not lawfully authorised to use;</li>
      <li>(g) harass, threaten or abuse Company personnel, delivery personnel or other Users;</li>
      <li>(h) post or transmit any information prohibited under Rule 3(1)(b) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021; or</li>
      <li>(i) engage in any activity constituting Account Abuse.</li>
      </ul>
      
      <h2 id="s17">17. Third-Party Services and Links</h2>
      <p>The Website may integrate or link to third-party services, including payment aggregators, courier partners, social-media platforms and analytics providers. Such services are governed by their own terms and privacy policies. The Company does not control and shall not be responsible for the content, availability or practices of third-party services, save to the extent that the Company is responsible for them under Applicable Law as a data fiduciary or as a seller.</p>
      
      <h2 id="s18">18. Warranties and Disclaimer</h2>
      <p>18.1 The Company warrants that the Products supplied by it (a) are genuine LORIUS Products; (b) conform to the declarations made on their labels; (c) are manufactured in compliance with Applicable Law, including the Cosmetics Rules, 2020; and (d) will be within their shelf life on the date of delivery.</p>
      <p>18.2 Save as expressly stated in Clause 18.1 and to the maximum extent permitted by Applicable Law, the Products and the Website are provided on an "as is" and "as available" basis, and the Company disclaims all other warranties, express or implied, including warranties that the Products will suit your personal preference, that any particular performance or longevity will be achieved on your skin, or that the Website will be uninterrupted, error-free or free of harmful components.</p>
      <p>18.3 Nothing in this Clause excludes any condition or warranty that cannot lawfully be excluded, including the conditions implied under the Sale of Goods Act, 1930 in favour of a Consumer, or any right under the Consumer Protection Act, 2019.</p>
      
      <h2 id="s19">19. Customer's Responsibilities for Safe Use</h2>
      <p>You undertake to read and follow the label, safety warnings and the <a href="#/disclaimer">Disclaimer</a> before using any Product, including performing a patch test, keeping Products away from flame, heat and children, and discontinuing use in case of any adverse reaction. The Company shall not be responsible for harm arising from misuse, use contrary to instructions, use of a Product after its expiry, use of a Product tampered with after delivery, or a known sensitivity to a declared ingredient.</p>
      
      <h2 id="s20">20. Limitation of Liability</h2>
      <p>20.1 To the maximum extent permitted by Applicable Law, the total aggregate liability of the Company, its directors, officers, employees and agents, arising out of or in connection with any Order, Product or use of the Website, whether in contract, tort (including negligence), statute or otherwise, shall not exceed the amount actually paid by you for the Product or Products giving rise to the claim.</p>
      <p>20.2 To the maximum extent permitted by Applicable Law, the Company shall not be liable for any indirect, incidental, special, punitive or consequential loss or damage, or for loss of profit, business, goodwill, opportunity or data, or for any loss arising from your reliance on any information on the Website.</p>
      <p>20.3 Nothing in these Terms shall limit or exclude the Company's liability: (a) for death or personal injury caused by its negligence; (b) for fraud or fraudulent misrepresentation; (c) under Chapter VI (Product Liability) of the Consumer Protection Act, 2019; or (d) for any other matter for which liability cannot lawfully be limited or excluded.</p>
      
      <h2 id="s21">21. Indemnity</h2>
      <p>You agree to indemnify, defend and hold harmless the Company, its affiliates, directors, officers, employees and agents from and against all claims, demands, actions, losses, liabilities, damages, costs and expenses (including reasonable legal fees) arising out of or relating to: (a) your breach of these Terms or any Policy; (b) your violation of Applicable Law or the rights of any third party; (c) your User Content; (d) unauthorised resale or misuse of Products by you; or (e) any fraudulent or false claim made by you.</p>
      
      <h2 id="s22">22. Force Majeure</h2>
      <p>22.1 The Company shall not be liable for any failure or delay in performance caused by events beyond its reasonable control (a <strong>"Force Majeure Event"</strong>), including acts of God, flood, earthquake, fire, epidemic or pandemic, war, terrorism, riot, civil commotion, strikes or lockouts (other than of its own employees), acts or restrictions of government or authorities, embargoes, disruption of courier, air or surface transport, shortage of raw materials, failure of utilities, telecommunication or internet networks, cyber-attacks, or failure of any third-party payment or hosting service.</p>
      <p>22.2 During a Force Majeure Event the Company's obligations shall be suspended for its duration. If the Force Majeure Event continues for more than thirty (30) days, either party may cancel any undispatched Order, and the Company shall refund the amount received for it in full.</p>
      
      <h2 id="s23">23. Communications and Consent to Contact</h2>
      <p>23.1 By providing your contact details and placing an Order, you consent to receive transactional communications (order confirmations, dispatch, delivery, one-time passwords, service messages and policy updates) by e-mail, SMS, telephone and WhatsApp, including on numbers registered on the National Customer Preference Register, to the extent such messages are transactional or service-related under the Telecom Commercial Communications Customer Preference Regulations, 2018.</p>
      <p>23.2 Promotional communications will be sent only where you have given separate, affirmative consent, which you may withdraw at any time using the unsubscribe link, by replying "STOP", or by writing to us.</p>
      <p>23.3 Communications sent to the e-mail address or mobile number registered with your account or Order shall be deemed received by you.</p>
      
      <h2 id="s24">24. Governing Law and Dispute Resolution</h2>
      <p>24.1 These Terms and all Orders are governed by and construed in accordance with the laws of the Republic of India.</p>
      <p>24.2 <strong>Amicable resolution.</strong> Before initiating any proceeding, you agree to first raise the dispute with the Company through the <a href="#/grievance">Grievance Redressal Policy</a> and to allow the Company the period of one month provided therein to resolve it.</p>
      <p>24.3 <strong>Consumers.</strong> Nothing in these Terms shall prevent a Consumer from filing a complaint before the District, State or National Consumer Disputes Redressal Commission having jurisdiction under sections 34, 47 or 58 of the Consumer Protection Act, 2019, including the Commission within whose jurisdiction the Consumer resides or personally works for gain, or from approaching the National Consumer Helpline or the Central Consumer Protection Authority. Subject thereto, the civil courts at New Delhi shall have exclusive jurisdiction.</p>
      <p>24.4 <strong>Business Purchasers.</strong> Any dispute between the Company and a Business Purchaser shall be referred to final and binding arbitration by a sole arbitrator appointed by mutual consent, failing which by the High Court of Delhi under section 11 of the Arbitration and Conciliation Act, 1996, or, if the parties so agree, under the rules of the Delhi International Arbitration Centre. The seat and venue of arbitration shall be New Delhi, the language shall be English, and the courts at New Delhi shall have exclusive supervisory jurisdiction.</p>
      
      <h2 id="s25">25. Amendment</h2>
      <p>25.1 The Company may amend these Terms and any Policy from time to time to reflect changes in law, business practice or the Products. The amended version shall be published on the Website with a revised effective date and, where the change is material, notified to registered Users by e-mail or by a prominent notice on the Website.</p>
      <p>25.2 The version of these Terms in force at the time you place an Order shall govern that Order. Continued use of the Website after publication of the amended Terms constitutes acceptance of them for all subsequent use and Orders.</p>
      
      <h2 id="s26">26. General</h2>
      <p>26.1 <strong>Entire agreement.</strong> These Terms and the Policies constitute the entire agreement between you and the Company in respect of their subject matter and supersede all prior communications.</p>
      <p>26.2 <strong>Severability.</strong> If any provision is held invalid or unenforceable by a court or Commission of competent jurisdiction, it shall be enforced to the maximum extent permissible and the remaining provisions shall continue in full force.</p>
      <p>26.3 <strong>Waiver.</strong> No failure or delay by the Company to exercise any right shall operate as a waiver of it.</p>
      <p>26.4 <strong>Assignment.</strong> You may not assign or transfer your rights under these Terms. The Company may assign or transfer its rights and obligations to an affiliate or successor on notice.</p>
      <p>26.5 <strong>Survival.</strong> Clauses relating to intellectual property, limitation of liability, indemnity, governing law and any other provision which by its nature should survive shall survive termination.</p>
      <p>26.6 <strong>Language.</strong> These Terms are drafted in English. Any translation is for convenience; in case of conflict the English version shall prevail, save where Applicable Law requires otherwise.</p>
      <p>26.7 <strong>Notices.</strong> Notices to the Company shall be sent to its registered office at 2nd Floor, B-265, Plot No. SU, North Ex-mall, Sector 9, Near Kadambari Apartment, Rohini, North West Delhi, Delhi 110085, with a copy by e-mail to <span className="fill">TO BE FILLED &mdash; legal notices e-mail</span>. Notices to you shall be sent to the e-mail address or mobile number associated with your account or Order.</p>
      <p>26.8 <strong>Customers outside India.</strong> The Website presently sells and ships only within India. If you access the Website from outside India, you do so on your own initiative and are responsible for compliance with your local law. Where the Company begins to sell into other territories, additional or different terms may apply to those sales and will be published before any such sale.</p>
      
      <h2 id="s27">27. Contact</h2>
      <p>For any question about these Terms, write to <span className="fill">TO BE FILLED &mdash; customer care e-mail</span> or contact the Grievance Officer as set out in the <a href="#/grievance">Grievance Redressal Policy</a>. Full contact details are on the <a href="#/contact">Contact Us</a> page.</p>
    </PolicyLayout>
  )
}
